name: Terraform Deploy (LocalStack)

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    # Credenciales dummy para el provider AWS (requeridas por el SDK)
    env:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1

    services:
      localstack:
        image: localstack/localstack:3.0-lite
        ports:
          - 4566:4566
        env:
          SERVICES: s3
          DEBUG: 1
          DEFAULT_REGION: us-east-1
        options: >-
          --health-cmd="curl -f http://localhost:4566/health || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Wait for LocalStack (healthcheck)
        run: |
          echo "Waiting for LocalStack service..."
          for i in {1..30}; do
            if curl -s http://localhost:4566/health | grep -q '"initialized": true'; then
              echo "✅ LocalStack ready"; exit 0; fi
            sleep 5
          done
          echo "❌ LocalStack not ready in time" && exit 1
      - name: Terraform init
        working-directory: infra
        run: terraform init -backend=false

      - name: Terraform plan
        working-directory: infra
        run: terraform plan -input=false -out=tfplan

      - name: Terraform apply
        working-directory: infra
        run: terraform apply -input=false -auto-approve tfplan

      # Paso opcional de verificación: listar buckets en LocalStack
      - name: Verify with AWS CLI (optional)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y awscli
          aws --endpoint-url=http://localhost:4566 s3 ls
