name: Terraform Deploy (LocalStack Real)

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted  # ← Tu propio runner con Docker
    
    services:
      localstack:
        image: localstack/localstack:2.3
        ports:
          - 4566:4566
        env:
          SERVICES: s3,ec2,lambda
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8
      
      - name: Wait for LocalStack
        run: |
          timeout 60 bash -c 'until curl -s http://localhost:4566/_localstack/health; do sleep 2; done'
      
      - name: Terraform workflow
        working-directory: infra
        env:
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_DEFAULT_REGION: us-east-1
        run: |
          terraform init
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan

      - name: Verify deployment
        run: |
          aws --endpoint-url=http://localhost:4566 s3 ls
